apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: app-sa
      containers:
        - name: app
          image: "{{ .Values.app.image }}:{{ .Values.app.tag | required ".app.tag is required" }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: app # the Service will expose all Pods with a label of app: app
  ports:
    - port: 80
      targetPort: 8080
      name: {{ .Values.gateway.protocol }}-app-port
  # type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with (dig "app-sa" "" .Values.workloadIdentity.gcpSaLinks) }}
    iam.gke.io/gcp-service-account: "{{ . }}"
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-sa-watch-jobs-rb
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: watch-jobs
subjects:
- kind: ServiceAccount
  name: app-sa
  namespace: {{ .Release.Namespace }}
