{{ if .Values.backup.enabled }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ include "corvina-app-[| .Name |].fullname" . }}-backup
  namespace: velero
spec:
  schedule: {{ .Values.backup.cron }}
  template:
    metadata:
      labels:
        argocd.argoproj.io/instance: none
    includedNamespaces:
      - corvina-app-[| .Name |]
    ttl: {{ .Values.backup.ttl | default "72h30m0s" }}
    storageLocation: {{ .Values.backup.storageLocation }}
    volumeSnapshotLocations:
      - {{ .Values.backup.snapshotLocation }}
{{ end }}
