{{ $PROTOCOL := (.Values.gateway.protocol | upper) }}
{{ $appHost := .Values.gateway.appHost }}
{{ if and (eq $PROTOCOL "HTTPS") (or (hasSuffix ".io" $appHost) (hasSuffix ".cloud" $appHost) (hasSuffix ".com" $appHost)) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.gateway.issuer.name }}
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: ISRG Root X1
    email: "monitoring@exorint.com"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: corvina-[| .Name |]-acme
    solvers:
      - dns01:
          cloudDNS:
            project: corvina-networking
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: corvina-[| .Name |]-app-certificate
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.gateway.certificateSecretName }}
  issuerRef:
    # The issuer created previously
    name: {{ .Values.gateway.issuer.name }}
  dnsNames:
  - {{ .Values.gateway.appHost | quote }}
  - {{ printf "*.%s" .Values.gateway.appHost | quote }}
{{ end }}

{{ if and (eq $PROTOCOL "HTTPS") (eq .Values.gateway.appHost "[| .Name |].corvina.mk") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: corvina-[| .Name |]-app-certificate
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.gateway.certificateSecretName }}
  issuerRef:
    kind: ClusterIssuer
    name: minikube-fake-letsencrypt-ca
  dnsNames:
  - {{ .Values.gateway.appHost | quote }}
  - {{ printf "*.%s" .Values.gateway.appHost | quote }}
{{- end }}