apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrator-job-{{ .Release.Revision }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: migrator-sa
      initContainers:
        - name: psql-wait
          image: "groundnuty/k8s-wait-for:1.3"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - "service"
            - "{{ .Release.Name }}-postgresql"
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
      containers:
      - name: service
        image: {{ .Values.service.image }}:{{ .Values.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 0.25
              memory: 256Mi
        envFrom:
        - configMapRef:
            name: service-config
        env:
          - name: START_FEATURES
            value: {{ .Values.migrator.envVar.START_FEATURES }}
          - name: PG_PASS
            valueFrom:
              secretKeyRef:
                name: name: {{ .Values.postgresql.global.postgresql.auth.existingSecret | default .Release.Name+"-postgresql" }}
                key: password
                optional: false
          [|- if .RedisEnabled |]
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-redis
                key: REDIS_PASSWORD
                optional: false   
          [|- end |]
      restartPolicy: OnFailure
  backoffLimit: 3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: migrator-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: migrator-role
rules:
- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: migrator-rb
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: migrator-role
subjects:
- kind: ServiceAccount
  name: migrator-sa
  namespace: {{ .Release.Namespace }}
