{{- define "corvina-app-[| .Name |].externalSecretsGenerator" -}}
apiVersion: generators.external-secrets.io/v1alpha1
kind: {{ ternary "Password" "Fake" (empty .Values.fakeExternalSecrets) }}
name: password-generator
{{- end }}

{{- if not .Values.fakeExternalSecrets }}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: password-generator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "corvina-app-[| .Name |].labels" . | nindent 4 }}
spec:
  allowRepeat: true
  length: 32
  noUpper: false
  symbols: 0
{{- else }}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Fake
metadata:
  name: password-generator
  namespace: {{ .Release.Namespace }}
spec:
  data:
    {{ toYaml .Values.fakeExternalSecrets | nindent 4 }}
{{- end }}
---

{{- if .Values.postgresql.global.postgresql.auth.existingSecret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.postgresql.global.postgresql.auth.existingSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "corvina-app-[| .Name |].selectorLabels" . | nindent 4 }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  dataFrom:
  - sourceRef:
      generatorRef:
        {{ include "corvina-app-[| .Name |].externalSecretsGenerator" . | nindent 8 }}
  refreshInterval: "0"
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: true
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        postgres-password: "{{`{{ trunc 16 .password  }}`}}"
        password: "{{`{{ trunc -16 .password }}`}}"
{{- end }}
---
{{- if .Values.redis.auth.existingSecret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.redis.auth.existingSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "corvina-app-[| .Name |].selectorLabels" . | nindent 4 }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  dataFrom:
  - sourceRef:
      generatorRef:
        {{ include "corvina-app-[| .Name |].externalSecretsGenerator" . | nindent 8 }}
  refreshInterval: "0"
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: true
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        redis-password: "{{`{{ .password  }}`}}"
{{- end }}
