apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: password-generator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "corvina-app-[| .Name |].labels" . | nindent 4 }}
spec:
  allowRepeat: true
  length: 16
  noUpper: false
  symbols: 0
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "corvina-app-[| .Name |].labels" . | nindent 4 }}
spec:
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: password-generator
  refreshInterval: "0"
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: true
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        postgres-password: "{{`{{ .password }}`}}"
        password: "{{`{{ .password }}`}}"
---
[|- if .RedisEnabled |]
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "corvina-app-[| .Name |].labels" . | nindent 4 }}
spec:
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: password-generator
  refreshInterval: "0"
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: true
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        REDIS_PASSWORD: "{{`{{ .password }}`}}"
[|- end |]