apiVersion: apps/v1
kind: Deployment
metadata:
  name: stasher-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stasher
  template:
    metadata:
      labels:
        app: stasher
    spec:
      serviceAccountName: stasher-sa
      initContainers:
        [|- if .RabbitEnabled |]
        - name: rabbitmq-wait
          image: europe-docker.pkg.dev/corvina-exorint/dockerhub-remote/groundnuty/k8s-wait-for:1.3
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - "service"
            - "{{ .Values.rabbitmq.clusterName }}"
          resources:
            {{ toYaml .Values.stasher.resources | nindent 12 }}
        [|- end |]
      containers:
        - name: stasher
          image: {{ .Values.stasher.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            - stash
          envFrom:
            - configMapRef:
                name: stasher-config-map
          env:
          {{- with .Values.stasher.extraCa }}
          - name: SSL_CERT_FILE
            value: /cacerts/ca.crt
          {{- end }}
          [|- if .RabbitEnabled |]
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.rabbitmq.clusterName }}-default-user
                key: password
                optional: false
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.rabbitmq.clusterName }}-default-user
                key: username
                optional: false
          [|- end |]
          volumeMounts:
          {{- with .Values.stasher.extraCa }}
          - name: extra-ca
            mountPath: /cacerts
          {{- end }}
          resources:
            {{ toYaml .Values.stasher.resources | nindent 12 }}
      volumes:
        {{- with .Values.stasher.extraCa }}
        - name: extra-ca
          secret:
            secretName: {{ .secret }}
            items:
            - key: ca.crt
              path: ca.crt
        {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stasher-config-map
  namespace: {{ .Release.Namespace }}
data:
  LOG_LEVEL: "{{ .Values.stasher.envVar.LOG_LEVEL }}"
  RABBITMQ_HOST: '{{ .Values.rabbitmq.clusterName }}'
  RABBITMQ_PORT: '5672'
  RABBITMQ_QUEUE: '{{ .Values.stasher.envVar.RABBITMQ_QUEUE }}'
  NETWORK_RETRY_INTERVAL: '{{ .Values.stasher.envVar.NETWORK_RETRY_INTERVAL }}'
  NETWORK_RETRY_MAX_TIMEOUT: '{{ .Values.stasher.envVar.NETWORK_RETRY_MAX_TIMEOUT }}'
  ACCEPTED_HTTP_RESULTS: '{{ .Values.stasher.envVar.ACCEPTED_HTTP_RESULTS }}'
  PERMANENT_HTTP_ERRORS: '{{ .Values.stasher.envVar.PERMANENT_HTTP_ERRORS }}'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stasher-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with (dig "stasher-sa" "" .Values.workloadIdentity.gcpSaLinks) }}
    iam.gke.io/gcp-service-account: "{{ . }}"
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: stasher-role
rules:
- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stasher-rb
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stasher-role
subjects:
- kind: ServiceAccount
  name: stasher-sa
  namespace: {{ .Release.Namespace }}
