apiVersion: apps/v1
kind: Deployment
metadata:
  name: stasher-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stasher
  template:
    metadata:
      labels:
        app: stasher
    spec:
      serviceAccountName: stasher-sa
      initContainers:
        - name: redis-wait
          image: "groundnuty/k8s-wait-for:1.3"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - "service"
            - "{{ .Release.Name }}-redis-headless"
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
        - name: init-password
          image: "blockstack/envsubst"
          env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.redis.auth.existingSecret | default "corvina-app-[| .Name |]-redis" }}
                key: redis-password
                optional: false
          command:
          - /bin/sh
          - -c
          args:
          - |
            set -euo pipefail
            envsubst < /tmp/stasher/config.yaml > /etc/stasher/config.yaml
          volumeMounts:
          - name: stasher-config-template
            mountPath: /tmp/stasher
          - name: stasher-config
            mountPath: /etc/stasher
          resources:
              limits:
                cpu: 100m
                memory: 64Mi
      containers:
        - name: stasher
          image: {{ .Values.stasher.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            - stash
          args:
            - --config
            - /etc/config/config.yaml
          env:
          {{- with .Values.service.extraCa }}
          - name: SSL_CERT_FILE
            value: /cacerts/ca.crt
          {{- end }}
          volumeMounts:
          - name: stasher-config
            mountPath: /etc/config
          {{- with .Values.service.extraCa }}
          - name: extra-ca
            mountPath: /cacerts
          {{- end }}
          resources:
            {{ toYaml .Values.stasher.resources | nindent 12 }}
      volumes:
        - name: stasher-config
          emptyDir: {}
        - name: stasher-config-template
          configMap:
            name: stasher-config-map
            items:
              - key: config.yaml
                path: config.yaml
        {{- with .Values.stasher.extraCa }}
        - name: extra-ca
          secret:
            secretName: {{ .secret }}
            items:
            - key: ca.crt
              path: ca.crt
        {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stasher-config-map
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    input:
      - type: redis
        host: {{ .Release.Name }}-redis-headless:6379
        key: {{ .Values.stasher.queue }}
        password: $REDIS_PASSWORD
        connections: 10
        batch_count: 100
        blocking_timeout: 600s
    output:
      - type: http
        http_status_codes: [200, 201, 202]
        http_error_codes: [501, 405, 404, 208, 505]
        retry_interval: 30
        max_queue_size: 1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stasher-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: stasher-role
rules:
- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stasher-rb
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stasher-role
subjects:
- kind: ServiceAccount
  name: stasher-sa
  namespace: {{ .Release.Namespace }}