apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: {{ .Values.k8sNamespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
        release-revision: '{{ .Release.Revision }}'
    spec:
      serviceAccountName: app-sa
      initContainers:
        - name: init
          image: "groundnuty/k8s-wait-for:1.3"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - "job"
            - "{{ .Release.Name }}-migrator-job-{{ .Release.Revision }}"
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
      containers:
        - name: app
          image: {{ .Values.app.image }}:{{ .Values.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            limits:
              cpu: 0.5
              memory: 256Mi
            requests:
              cpu: 0.1
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: {{ .Values.k8sNamespace }}
spec:
  selector:
    app: app # the Service will expose all Pods with a label of app: app
  ports:
    - port: 80
      targetPort: 8080
      name: {{ .Values.gateway.protocol }}-app-port
  # type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: {{ .Values.k8sNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-sa-watch-jobs-rb
  namespace: {{ .Values.k8sNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: watch-jobs
subjects:
- kind: ServiceAccount
  name: app-sa
  namespace: {{ .Values.k8sNamespace }}