repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

helmDefaults:
  timeout: 1800
  kubeContext: {{ .StateValues.kubeContext }}

releases:
  - name: istio-discovery
    chart: istio/istiod
    version: 1.20.4
    kubeContext: {{ .StateValues.kubeContext }}
    namespace: {{ if hasKey .StateValues "namespace" }}{{ .StateValues.namespace }}{{ else }}{{ .StateValues.releaseName }}{{ end }}
    labels:
      pkg: istio
    values:
      - istio-discovery.values.yaml.gotmpl
    transformers:
    - apiVersion: builtin
      kind: AnnotationsTransformer
      metadata:
        name: istio-sync-wave
      annotations:
        argocd.argoproj.io/sync-wave: "-10000"
      fieldSpecs:
      - path: metadata/annotations
        create: true
  - name: {{ .StateValues.releaseName }}
    chart: corvina-app-[| .Name |]
    kubeContext: {{ .StateValues.kubeContext }}
    namespace: {{ if hasKey .StateValues "namespace" }}{{ .StateValues.namespace }}{{ else }}{{ .StateValues.releaseName }}{{ end }}
    labels:
      pkg: app
    values:
      - base.yaml.gotmpl
      - values.{{ .Environment.Name }}.yaml
      - envs/hotfix-branch-tags.yaml
      {{- if eq .Environment.Name "minikube" }}
      - envs/this-branch-tags.yaml
      {{- end }}
    transformers:
    - apiVersion: builtin
      kind: AnnotationsTransformer
      metadata:
        name: argocd-annotate-job-for-recreation
      annotations:
        argocd.argoproj.io/sync-options: "Force=true,Replace=true"
      fieldSpecs:
      - kind: Job
        group: ""
        path: metadata/annotations
        create: true

environments:
  internal-qa:
    values:
      - envs/common-defaults.yaml
      - envs/internal-qa.yaml
  us:
    values:
      - envs/common-defaults.yaml
      - envs/us.yaml
  minikube:
    values:
      - envs/common-defaults.yaml
      - envs/minikube.yaml
  internal:
    values:
      - envs/common-defaults.yaml
      - envs/internal.yaml
