#!/bin/bash
SRC="."
DST="../static/docs"
DST_IMG="../public/docs"
MARKED_BIN="node ./marked_runner.js"
echo BUILDING DOCUMENTATION

BRAND=brand-name
LOCALE=en

buildBrand() {
	for md in $SRC/$BRAND/$LOCALE/*.md
	do
		(
		 OUTNAME=$(basename $md .md).html
		 mkdir -p $DST/$BRAND/$LOCALE 
		 OUTPATH=$DST/$BRAND/$LOCALE/$OUTNAME
		 echo - Compiling: $md "=>" $OUTPATH;
		 echo "<!-- AUTOMATICALLY GENERATED : DO NOT EDIT THIS FILE -->" > $OUTPATH
		 $MARKED_BIN $md >> $OUTPATH
		) &
	done
	wait
	cp -a  $SRC/$BRAND/$LOCALE/img $DST/$BRAND/$LOCALE

	mkdir -p $DST_IMG/$BRAND/$LOCALE
	cp -a  $SRC/$BRAND/$LOCALE/img $DST_IMG/$BRAND/$LOCALE
}

buildBrandIndex() {
	echo "/** This file has been automically generated by build-docs.sh. DO NOT EDIT IT MANUALLY **/" > $DST/$BRAND/index.ts
	for file in `find $DST/$BRAND/en -type f -iname "*.html"`
	do
		echo "export const `basename $file .html`Html = async (locale:string) => (await import(\`./\${locale}/`basename $file?raw`\`) ).default" >> $DST/$BRAND/index.ts
	done
}

# all other brands
for BRAND in `find  brands -mindepth 1 -maxdepth 1 -type d`
do
  printf "Build docs for brand $BRAND\n"
  for LOCALE in `cd $SRC/$BRAND && find ./ -mindepth 1 -maxdepth 1 \( -type l -o -type d \) -exec bash -c "basename \"{}\"" \;`
    do
      printf "Build docs for locale $BRAND/$LOCALE\n"
      (
        echo "Build docs for brand $BRAND/$LOCALE"
        buildBrand
      ) &
      wait
    done
    echo "Build brand index $BRAND"
    buildBrandIndex
done

wait

# link linked brands
for LINKED_BRAND in $(find  $SRC/brands -mindepth 1 -maxdepth 1 -type l | sed "s/$SRC\///")
do
	echo  $LINKED_BRAND $SRC/$LINKED_BRAND $(readlink $SRC/$LINKED_BRAND)
	ln -nsf $(readlink $SRC/$LINKED_BRAND) $DST/$LINKED_BRAND
done
